### ISSUE TITLE
Unique foreignID

### ISSUE THREAD

**Issue by massimilianoregis** [sumup/sumup-android-sdk#101]
the foreign id is unique but.... if my transaction failed?
is it needed this id was unique only for success transaction

**Comment by JullianSU** [comment]
Hi Massimiliano, 

Thank you for your message, the foreign transaction ID **must** be different for every transaction attempt if your transaction fails for any reason, a new ID must be provided when another attempt occurs. 

Many thanks,

**Comment by massimilianoregis** [comment]
very funny answer...
please take one second of your time for thinking about this issue.... do you think that this one is a great business logic or it is a business logic fault?
I think that this one is a business logic error. why? because if one of my customer have a problem to the card and retry with another one. my foreign key is (obviously) the same. your primary key is different but my foreign no.

please take me a better answer

**Comment by massimilianoregis** [comment]
Julian..... after one month... no one answer to my issue.
the last android-sdk update was 4 months ago!

please Julian. tell me the truth.
I am working for a new startup on US and I need a very stable solution...
do you think that android sdk exists or is it a removed project?

**Comment by massimilianoregis** [comment]
two months without an answer

**Comment by JullianSU** [comment]
Hi Massimiliano, 

Thank you for your message, the Android project is active and improving constantly. The way we are handling foreign transaction ID is well documented and we have no plans to change it at the moment. 

However, we are taking your feedback into consideration

Many thanks.

**Comment by massimilianoregis** [comment]
ok, for the foreign key... but you have a lot of issue without any kind of
answer... the last push was 4 months ago: it seems a very little for an
active project.

**Comment by massimilianoregis** [comment]
are you sure that is the project active? (see the attachment)

I have to take a choice in the next months: square or sumup.
