### ISSUE TITLE
Timeout on Status Activity

### ISSUE THREAD

**Issue by shaksp** [sumup/sumup-android-sdk#107]
Hi,

We are using the built in Status Screens on the SDK for a donation kiosk app rather than our own Payment status page.

What we would like is if a user makes a payment or cancels a payment and then walks away without Skipping/Dismissing the Status Page, the page times out and returns to the App after a timeout period.
Currently it just stays on the Status Page until someone else Skips/Dismisses it.

Also - I note alot of the issues with bluetooth locks up on the reader (AIRE205) is if it receives two commands close together - e.g. prepare and transaction commands. It needs a wait time between needs to clearing down a transaction before preparing for another.

Kind Regards,

**Comment by JullianSU** [comment]
Hi shaksp,

It looks like you are using an unattended use case, can you please describe more at integration@sumup.com

Many thanks,
