### ISSUE TITLE
Print Receipt on Bluetooth Printer (Bixolon)

### ISSUE THREAD

**Issue by alexschled** [sumup/sumup-android-sdk#115]
Hello,

is it possible to print the payment receipt on a bixolon spp-r200ii printer instead of sending it via e-mail? 

Thank you

**Comment by JullianSU** [comment]
Hi @alexschled, 

Thank you for your message, the SDK is not made to connect directly with the printer, it is the responsibility of your application to communicate with the printer. The receipt that we send is not made to be printed. You can use what is in the response ok the SDK/API or use our [Receipt REST API](https://developer.sumup.com/rest-api/#tag/Receipts) to build your own receipt. 

Many thanks,
