### ISSUE TITLE
Remove or update Dagger

### ISSUE THREAD

**Issue by ndmt** [sumup/sumup-android-sdk#12]
Hello,

I have an issue with the SDK when I try to run Proguard.

`Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForProdRelease'. > java.io.IOException: Can't write [/*****/app/build/intermediates/transforms/proguard/prod/release/jars/3/1f/main.jar] (Can't read [/*****/.gradle/caches/modules-2/files-2.1/com.squareup.dagger/dagger/1.2.2/e8f912ee19ad84958510883ea191135276b091f8/dagger-1.2.2.jar(;;;;;;**.class)] (Duplicate zip entry [dagger/a.class == dagger-1.2.2.jar:dagger/Lazy.class]))`

I'm using dagger 2.+ and I think the dagger package doesn't like to be provided by an other dependency (dagger 1) when proguard is running.

Any solutions ?

Thanks.

**Comment by konradfeketesumup** [comment]
Hi,
I apologise for the lateness of my reply on this channel. 
As stated by my colleague before in a private message, there is no workaround for this issue at the moment as both classes are in the respective core packages. Moving to Dagger 2 is on our roadmap however for now there is no scheduled release date. At the moment we only support Dagger 1.
Best regards

**Comment by santiago91ams** [comment]
Hello!! I have the same problem, it looks like sumup android sdk is incompatible with dagger 2.+. Do you know when it will have support for dagger2 ?

**Comment by gk5885** [comment]
@konradfeketesumup, the workaround is to stop repackaging Dagger (1 or 2).  Unless you using something like [the Maven shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/) or [JarJar](https://github.com/shevek/jarjar), that is a bad practice for any dependency.

**Comment by ultrah** [comment]
@gk5885 thank you for the suggestion, I gave this a try using JarJar, but I seem to be missing something. Maybe you can help me out?

My first try was to simply move everything in both dagger and dagger-compiler to a different package and manually edit META-INF/services/javax.annotation.processing.Processor to point to the correct sumup.dagger.internal.codegen.* package

`rule dagger.** sumup.dagger.@1`

This breaks injection though, the InjectAdapters are simply not generated. Any clue why or how to debug?


My seccond attempt was to only move the Annotations:

`rule dagger.Lazy sumup.dagger.Lazy
rule dagger.MembersInjector sumup.dagger.MembersInjector
rule dagger.Module sumup.dagger.Module
rule dagger.Provides sumup.dagger.Provides
rule dagger.Provides$Type sumup.dagger.Provides$Type
rule dagger.internal sumup.dagger.internal
rule dagger.producers sumup.dagger.producers

This works and enables compatibility with Dagger 2 in the host app, but breaks compatibility with Dagger 1 as the rest of the files obviously are duplicate now.

Any hints on how to proceed?

**Comment by gk5885** [comment]
I think it sounds like things are getting invoked in the wrong order.  I would think that you'd want to invoke jarjar _after_ the annotation processor runs, not before.

**Comment by ultrah** [comment]
Thanks, I'll try in this direction. I assume this is for the first of the two attempts that I made here? 

Also I would assume that this is a common problem with Dagger... do you know of anyone else who has solved this issue and how?

**Comment by vfoixcable** [comment]
From upcoming sdk version 2.4.0, the sdk wont rely on any dagger version anymore

**Comment by WojtiDev89** [comment]
When are you planning to release sdk version 2.4.0?

**Comment by vfoixcable** [comment]
version 2.4.0 will be released end of week 37 / beginning of week 38!

**Comment by vfoixcable** [comment]
released: https://github.com/sumup/sumup-android-sdk/releases/tag/v2.4.0
