### ISSUE TITLE
Please make TransactionInfo.Card accessible

### ISSUE THREAD

**Issue by WindohsCrasher** [sumup/sumup-android-sdk#13]
When requesting SumUpAPI.Response.TX_INFO, a lot of transaction information is given back.

What I'd like to achieve now is that I can print the last four digits of the used card and the card type on a receipt. The class TransactionInfo has a member called "getCard()" - however, since the class TransactionInfo.Card is private, the returned object cannot be used and I can't get the information which I'd like to print.

**Comment by konradfeketesumup** [comment]
Hello!

Thank you for your report! There is indeed a little mistake we need to fix. Nevertheless, please note that the returned transaction data is not sufficient for creating compliant printable receipts. Please use the receipt functions provided by the SDK (Send receipt via mail or text message) for the time being. Soon, we will make a dedicated API for receipts available where appropriate data will be supplied for receipt generation. 

Best regards

**Comment by vfoixcable** [comment]
fixed since release 2.0.0
