### ISSUE TITLE
Difference between "sumup-android-sdk" and "sumup-android-api"?

### ISSUE THREAD

**Issue by jmar83** [sumup/sumup-android-sdk#131]
When i visit both repositories, i just see, more or less, the same thing: a hello-world demo application for android.

So what's the difference between that both repositories.

Thank you very much for your feedback.

**Comment by jmar83** [comment]
`sdk` my be the newer version, right? and the `api` is obsolete...?

`sdk` current release version:
3.3.2

`api` current release version:
1.4.0

Is the correctly?

**Comment by jmar83** [comment]
Are there any other differences??

**Comment by Handballermann** [comment]
(i guess) the API example calls the standard sumup app. 

the sdk example has the app included.

**Comment by jmar83** [comment]
Thanks!
