### ISSUE TITLE
How to use it with different activities - login/logout on activity A, payment on activity B?

### ISSUE THREAD

**Issue by xaxada-github** [sumup/sumup-android-sdk#135]
Hello

How to use it with different activities?

We have a `SettingsActivity` with SumUp login- and logout-buttons. And that's the activity that will be used by the SumUp library to initialize and login. (So the first steps they are required)

But: The payment process will be initialized on a completly other activity `Main3Activity` - and there is the issue: If the program is on `Main3Activity`, the `SettingsActivity` was "killed"...

The SumUp Android lib is NOT open-source and not well documented - so i can't customize it...

Thank you very much for your feedback.

With best regards,
Jan

**Comment by vladaman** [comment]
You first proceed with Authentication (in your Settings activity) and then once authenticated the SumUp library stores credentials (auth tokens).
Later in any other activity you call intent to open SumUp payment. You no longer need to proceed with authentication. This was done already.

_We found SumUp library well documented and the integration was a breeze. I understand why library is not Open source. It's payment related and compliance and quality is important_ 

**1. Initialize**
```
SumUpState.init(this);
```
**2. Authenticate user**
```
SumUpLogin sumupLogin = SumUpLogin.builder(mAffiliateKey).build();
SumUpAPI.openLoginActivity(MainActivity.this, sumupLogin, 1);
```
3. In any other activity call Intent to **proceed with a payment with** 
```
SumUpPayment payment = SumUpPayment.builder()
...
SumUpAPI.checkout(MyPaymentActivity.this, payment, 2);
```

**Comment by xaxada-github** [comment]
Hello Vladimir

 

Thank you very much, will look about it!

 

 

With best regards from Switzerland,

Jan

--

Mit freundlichen Grüssen / With kind regards

Jan Marti
Development


INTRO (Schweiz) AG
Langfeldstrasse 24
CH-4528 Zuchwil

Phone:  +41 41 511 00 46
E-Mail: dev@intro.ch <mailto:dev@intro.ch>  
Skype:  live:.cid.743a780d7f7a1802

 

 

 

 

Von: Vladimir Vlach <notifications@github.com> 
Gesendet: Mittwoch, 15. Juli 2020 09:04
An: sumup/sumup-android-sdk <sumup-android-sdk@noreply.github.com>
Cc: xaxada-github <dev@xaxada.com>; Author <author@noreply.github.com>
Betreff: Re: [sumup/sumup-android-sdk] How to use it with different activities - login/logout on activity A, payment on activity B? (#135)

 

You first proceed with Authentication (in your Settings activity) and then once authenticated the SumUp library stores credentials (auth tokens).
Later in any other activity you call intent to open SumUp payment. You no longer need to proceed with authentication. This was done already.

We found SumUp library well documented and the integration was a breeze. I understand why library is not Open source. It's payment related and compliance and quality is important

1. Initialize

SumUpState.init(this);

2. Authenticate user

SumUpLogin sumupLogin = SumUpLogin.builder(mAffiliateKey).build();
SumUpAPI.openLoginActivity(MainActivity.this, sumupLogin, 1);

3.	In any other activity call Intent to proceed with a payment with

SumUpPayment payment = SumUpPayment.builder()
...
SumUpAPI.checkout(MyPaymentActivity.this, payment, 2);

**Comment by martijintro** [comment]
Thank you very much!!

**_"We found SumUp library well documented"_**

Not really i.m.o.

For example, "skipSuccessScreen" is not in the hello-world-demo-app...

But maybe there is an official documentation, e.g. "JavaDoc". If yes, can you give me the link please?

**Comment by martijintro** [comment]
Hmmm...? ;-)
