### ISSUE TITLE
How to login without user interaction?

### ISSUE THREAD

**Issue by jayjupdhig** [sumup/sumup-android-sdk#143]
How to login without user interaction?

**Comment by alexschled** [comment]
We struggled a little bit, too.

Just read this post
[Issue45](https://github.com/sumup/sumup-android-sdk/issues/45)

It's required to get in contact with sumup to activate the payment scope. Afterwards you simple request a token in your code and skip the user interaction

**Comment by jayjupdhig** [comment]
thx
