### ISSUE TITLE
Currency settings

### ISSUE THREAD

**Issue by Jacksotnik** [sumup/sumup-android-sdk#16]
Hello. Is it possible to configure currency somewhere in account, and not to set as parameter for SumUpPayment.builder()?

For to have something like this:
```
SumUpPayment payment = SumUpPayment.builder()      
            .affiliateKey("YOUR_AFFILIATE_KEY")
            .productAmount(1.23)
            .foreignTransactionId(UUID.randomUUID().toString())
            .build();
SumUpAPI.openPaymentActivity(MainActivity.this, payment, 1);
```

**Comment by konradfeketepayleven** [comment]
Hi,

Thank you for your inquiry.
No, this is not possible. The currency shall be specified in each payment request.
For security reasons, we always check the provided currency against the currency defined for your merchant account.
Best

**Comment by Jacksotnik** [comment]
Ok. Thank's for answer
