### ISSUE TITLE
How can i parce TransactionInfo

### ISSUE THREAD

**Issue by Jacksotnik** [sumup/sumup-android-sdk#17]
Hello, can you please provide small example, how can i parce TransactionInfo

So in answer i have string
`AData.getParcelable(SumUpAPI.Response.TX_INFO));`

But i need to have TransactionInfo object 
something like this 
`TransactionInfo txInfo = new TransactionInfo(AData.getParcelable(SumUpAPI.Response.TX_INFO));`

how can i get it?

**Comment by ultrah** [comment]
Like it is done here: https://github.com/sumup/sumup-android-sdk/blob/master/app/src/main/java/com/sumup/sdksampleapp/MainActivity.java#L83

**Comment by Jacksotnik** [comment]
Sorry, i didn't check it. Thank you :)

**Comment by Jacksotnik** [comment]
Sorry, it's again me) And do we have any possibility to parce vTXInfo.getCard()?
In Card class i can se public metods, but it's unavailable for to call from my app
```
public String getLast4Digits() {
    return this.last4Digits;
}

public String getType() {
  return this.type;
}
```

**Comment by ultrah** [comment]
This is a bug, it will be fixed in the next SDK release
