### ISSUE TITLE
Configure machine without starting a payment

### ISSUE THREAD

**Issue by ddello32** [sumup/sumup-android-sdk#19]
It would be really useful for my use case to be able to connect with Pinpad and configure the machine without really starting a payment. My machines are shared between multiple users and they each have one device, at the start of the day they get one machine (that may or may not be the one they were using the day before). Having the ability to sync before operation starts would speed up our process (specially for those using p2 cable instead of bluetooth). I can create a mock transaction and tell users to cancel it, but it would be better if I was able to access the configuration flow without a payment transaction.

**Comment by vfoixcable** [comment]
`prepareForCheckout` is serving this purpose since version 2.3.0
(see https://github.com/sumup/sumup-android-sdk/releases/tag/v2.3.0 and https://github.com/sumup/sumup-android-sdk#3-prepare-the-sumup-card-terminal-in-advance)
