### ISSUE TITLE
Response fields documentation not correct 

### ISSUE THREAD

**Issue by philipflohr** [sumup/sumup-android-sdk#20]
The described return value
SumUpAPI.Response.ResultCode.SUCCESSFUL
is actually called TRANSACTION_SUCCESSFUL

**Comment by vfoixcable** [comment]
From SDK 2.1.0, `TRANSACTION_SUCCESSFUL` is deprecated in favor of `SUCCESSFUL` : https://github.com/sumup/sumup-android-sdk/releases/tag/v2.1.0
