### ISSUE TITLE
Transparent login doesn't work

### ISSUE THREAD

**Issue by hiagodotme** [sumup/sumup-android-sdk#205]
Dear friends,

I'm trying to integrate with SumUp's Android SDK, when I connect using username and password everything happens normally. The charge is made and the amount made available in the Sumup application.

It turns out that I would like to use transparent authentication, I perform the entire procedure to obtain a valid access token, but when trying to login I get the following message:

- (SourceFile:32)@main | Event rpcEventLogin - Reason: Lamentamos, mas estamos com um erro inesperado. Por favor, saia da conta e tente novamente iniciar a sessão ou entre em contato com o Suporte (código: UKN-2E7BG)

The message is in Portuguese due to my location but I believe the error code UKN-2E7BG helps with something.

- payments - Allows you to make payments by creating and processing payment checkouts.
- payment_instruments - Allows you to save customers and tokenize their payment cards for a specific merchant user's account.

Could this be the reason I couldn't login transparently?

**Comment by ameinhardt** [comment]
https://github.com/sumup/sumup-ios-sdk/issues/118 says

> Additionally, the authorisation request should have default (transactions.history, user.app-settings, user.profile_readonly) and payments scopes specified in order to get the access token working with the transparent authentication.

**Comment by hiagodotme** [comment]
Thanks @ameinhardt I got support from the SumUp development team here in Brazil and they helped me get it working.
