### ISSUE TITLE
openCardReaderPage is empty and I get no error

### ISSUE THREAD

**Issue by Henner** [sumup/sumup-android-sdk#209]
Hi,

my card reader page is empty (blank white screen) after calling:
SumUpAPI.openCardReaderPage(MainActivity.this, 4);

experianced on SUNMI T2s 

I reflected the following settings:

implementation "com.google.android.gms:play-services-location:19.0.1"
coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:1.1.5"
implementation 'com.sumup:merchant-sdk:4.2.0'

android {
  compileOptions {
    coreLibraryDesugaringEnabled true
  }
}

The SumUp App from the Appstore runs fine on this device.

All I get is:
 (SumUpButtonBase.kt:44)@main | Button text cannot exceed 20 characters

**Comment by Henner** [comment]
I was missing:
    <uses-permission android:name="android.permission.BLUETOOTH" />

I only had:
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

**Comment by haris-dautovic** [comment]
Hi @Henner,

I have the same problem. What was the problem here? 

Thanks!

**Comment by Henner** [comment]
this is still unresolved!

I do have this problem on several accounts - but not on all.
My error message is: (SumUpButtonBase.kt:44)@main | Button text cannot exceed 20 characters

Creating a new account did solve this 2 times. I have no answer from integration@sumup.com

What is your error?

**Comment by Henner** [comment]
still unresolved

**Comment by haris-dautovic** [comment]
It is the same error for me and I also tried different accounts, not all accounts have this problem. At the first point I though this is a problem related to integration but it seems it is account related thing.
