### ISSUE TITLE
No error if application id is unknown to sumup

### ISSUE THREAD

**Issue by philipflohr** [sumup/sumup-android-sdk#21]
1. Go to the sumup developer page
2. create api key, add application identifier which does not match the identifier of the app you want to use with sumup.
3. Integrate sumup into your app
4. Try to use sumup from inside your app
--> Login fails with "Invalid username/password" message

In my opinion there should be a more usefull error message or the activity should return with a RESULT_CODE like ERROR_INVALID_IDENTIFIER

**Comment by vfoixcable** [comment]
Thanks for pointing out this issue. We will investigate internally and fix this in a future version of the SDK
