### ISSUE TITLE
Unexpected error when I try auto login by set accessToken in SumUpPayment object

### ISSUE THREAD

**Issue by welovehangers** [sumup/sumup-android-sdk#23]
Hello, 

I work on your SdkSampleApp to have auto login connecting SumUp Card Terminal. 
I need your help to understand what’s wrong.

If I use login form, app works great :) 

I try to log in with SumUp Android SDK automaticaly using AccesToken. When I add this line to SumUpPayment instance : 

.accessToken(« 5e932de6ca61cf1c243746024f09881d12f9e655fbfe6eef3b1b302e33e1 ») 

I have this line in Logcat :

03-28 19:19:13.992 12573-12573/com.sumup.sdksampleapp E/SumUp: (SourceFile:180)@main | Event rpcEventLogin - Reason: Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-3R68N)

Before I create as recommended Android credentials and I add new application identifier : com.sumup.sdksampleapp

To get accessToken, I call your oAuth api : 

Request : 
URL : https://api.sumup.com/oauth
METHOD : post
Header : Content-Type : application/json
Body : 

{
	"id":"CC6S66X",
	"name":"H",
	"client_id":"nHB8HerA8XGgpTUy86BQvBn6YgcP",
	"client_secret":"b73786fe21438eb35d2b1e4292c674ef60821f337986dcbbcafd829790ee8317",
	"application_type":"android",
	"redirect_uris":["http://www.hangers.io/sumup"]
}

Response : 
{
  "access_token": "5e932de6ca61cf1c243746024f09881d12f9e655fbfe6eef3b1b302e33e1",
  "token_type": "Bearer",
  "expires_in": 3600
}

Thanks for your help.

Benjamin

**Comment by flixbernard** [comment]
Hello Benjamin,

I'm stuck exactly at the same point. Did you finally succeed to solve the problem ?
Thank you in davance for your help.

Best regards,

Félix

**Comment by alaporterie** [comment]
Hi, I get the same issue when using transparent authentication.

"Event rpcEventLogin - Reason: Nous sommes désolés, une erreur est survenue. Merci de vous déconnecter pour ensuite essayer de vous reconnecter ou de contacter le service client (code: UKN-1JJ3U)"
Can you help me please?

I used SDK 3.0.0.

Thank you,
Anthony
