### ISSUE TITLE
Build failed after adding the com.sumup:merchant-sdk dependency (net.openid.appauth.AuthorizationService could not be resolved)

### ISSUE THREAD

**Issue by petergoczan** [sumup/sumup-android-sdk#233]
Hi,

I want to integrate the API into my application, but as soon as I add `implementation("com.sumup:merchant-sdk:5.0.3")` to my app/build.gradle, I'm getting the following build error:

`error: ComponentProcessingStep was unable to process 'com.myapp.MyApplication_HiltComponents.SingletonC' because 'net.openid.appauth.AuthorizationService' could not be resolved.`

  `Dependency trace:
      => element (CLASS): com.sumup.identity.auth.implementation.di.HiltAuthModule.Companion
      => element (METHOD): provideAuthorizationService(android.content.Context)
      => type (EXECUTABLE method): (android.content.Context)net.openid.appauth.AuthorizationService
      => type (ERROR return type): net.openid.appauth.AuthorizationService`

`If type 'net.openid.appauth.AuthorizationService' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'net.openid.appauth.AuthorizationService' is on your classpath.` 
  
 I have found that the reason might be that the `net.openid.appauth.AuthorizationService` class, which is a dependency of the SumUp SDK, is missing from my project. However if I add it as a dependency as well (`implementation("net.openid:appauth:0.11.1")`), I'm getting a different error:
`Caused by: java.lang.RuntimeException: Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.
	at com.android.build.gradle.internal.tasks.manifest.ManifestHelperKt.mergeManifests(ManifestHelper.kt:125)
	at com.android.build.gradle.internal.tasks.manifest.ManifestHelperKt.mergeManifests$default(ManifestHelper.kt:46)
	at com.android.build.gradle.tasks.ProcessApplicationManifest.doTaskAction(ProcessApplicationManifest.kt:162)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:79)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:78)`

**Comment by petergoczan** [comment]
FYI I have "debugged" this by creating a new project and adding the dependencies and the code changes one by one, so I can now see where this is breaking. This is still not resolved, but if I remove the hilt implementation from the app (not the dependencies, just all the @Inject stuff, the @HiltAndroidApp and the @AndroidEntryPoint), the the code works again.

**Comment by petergoczan** [comment]
Checking this further, I can still use Hilt if I downgrade the SumUp SDK version to 4.3.0. Please check why it doesn't work with newer versions.

Details:
- hilt-android-compiler: 2.47
- hilt-android: 2.48
- agp: 8.7.0
- gradle: 8.9
- compileSdk: 34
- targetSdk: 34
- Java: 17.0.13

**Comment by mkutlev** [comment]
Hi @petergoczan,
Thank you for reporting the problem. Your detailed explanation helped us to reproduce the issue.
We are working on a fix.

**Comment by mkutlev** [comment]
Update: We will add the fix to the next released.

**Comment by dszabome** [comment]
@mkutlev that's great, thank you!
When do you expect to publish that upcoming release?

**Comment by mkutlev** [comment]
> @mkutlev that's great, thank you! When do you expect to publish that upcoming release?

Hopefully in Q1 2025.

**Comment by petergoczan** [comment]
@mkutlev thanks for your help, unfortunately in the meantime we can't progress with our project, the checkout functionality is not working with the downgraded SDK version. Could you please suggest some changes in my setup in order to make this work with the current latest SDK version? We are blocked on this 🙏

**Comment by mkutlev** [comment]
@petergoczan 

> @mkutlev thanks for your help, unfortunately in the meantime we can't progress with our project, the checkout functionality is not working with the downgraded SDK version. Could you please suggest some changes in my setup in order to make this work with the current latest SDK version? We are blocked on this 🙏

To avoid the compile problem you can try creating the missing class. Having a fake version of this class won't affect the functionality of the library.

Try with this:

```
// The package should be exactly like the missing class
package net.openid.appauth

import android.content.Context

// This is the constructor used in provideAuthorizationService
class AuthorizationService constructor(context: Context)
```
