### ISSUE TITLE
Payments fail with wrong error message if account is not fully verified

### ISSUE THREAD

**Issue by philipflohr** [sumup/sumup-android-sdk#24]
Steps to reproduce:
1. Create an account, get a card reader
-> Enter just the minumum of required data into the account
2. Integrate payments in an app
--> Works as expected
3. Wait for the "Please verify your account" mail
--> Payments in your app fail with a "communication error" and an empty tag message
4. Open the Sumup App
--> The app shows the "Your account is not verified" message
5. click it away
6. Use your own app again
--> Works again

**Comment by vfoixcable** [comment]
Thanks for reporting. We will investigate internally.
