### ISSUE TITLE
Android Permissions

### ISSUE THREAD

**Issue by tscheiki** [sumup/sumup-android-sdk#25]
Hi, 

does this SDK automatically add new permissions to the app? If yes, why do you need them?

E.g.:
- android.permission.RECORD_AUDIO
- android.permission.READ_PHONE_STATE
- android.permission.GET_ACCOUNTS

**Comment by vfoixcable** [comment]
Hi,

READ_PHONE_STATE and RECORD_AUDIO are used for the readers still relying on the audio cable. 

GET_ACCOUNTS was used in the old way of login but seems not to be used anymore and therefore can probably be removed in a future version of the sdk. 

Thanks for the input. We will take action internally

**Comment by lubostar** [comment]
Hi,
did you consider removing those permissions yet?

I don't really need them for my scenario and Google is giving me a hard time because of it as they consider those permissions "Dangerous".

**Comment by ubeyou** [comment]
sumsub android.permission.RECORD_AUDIO causes google app submission to ask for video to explain how you going to use it. is it still neccessary?
```

Your app uses the FOREGROUND_SERVICE_MICROPHONE permission. You can only use this permission if your app performs tasks noticeable to the user when they're not directly interacting with your app.

Microphone
What tasks require your app to use the FOREGROUND_SERVICE_MICROPHONE permission?

```

**Comment by cyrilcolinet** [comment]
Hi there, same issue there

Any updates?
