### ISSUE TITLE
datatype double for productAmount?

### ISSUE THREAD

**Issue by MarcusWolschon** [sumup/sumup-android-sdk#27]
SumUpPayment.productAmount only allows a double value as the amount.
Currency values should NEVER be a double because many values can not be encoded as a floating point number.
e.g. the "0.1 €" or "0.5 €" can not be expressed in floating point with a binary system at all.

It should under no circumstanced be encouraged for users of such an API to use float or double for monetary values.

A BigDecimal would be appropriate.

**Comment by vfoixcable** [comment]
Thanks for your suggestion. We will investigate internally.
