### ISSUE TITLE
example for onActivityResult incorrect

### ISSUE THREAD

**Issue by MarcusWolschon** [sumup/sumup-android-sdk#28]
readme.md has an example for onActivityResult  in 
"4. Handle payment result"

  @Override
   protected void onActivityResult(int requestCode, int resultCode, Intent data) {
      if (requestCode == 2 && data != null) {
         // Handle the response here
      }
   }

At the end the example reads
           int resultCode = getIntent().getExtras().getInt(SumUpAPI.Response.RESULT_CODE);
where it would usually be
            final int code = data.getExtras().getInt(SumUpAPI.Response.RESULT_CODE);

**Comment by vfoixcable** [comment]
Thanks for your input. Will be considered.
