### ISSUE TITLE
Question about your example

### ISSUE THREAD

**Issue by Isabellle** [sumup/sumup-android-sdk#29]
Tell me if I'm wrong, but I guess the requestCode 2 should be used instead of 1 ?

`SumUpAPI.openPaymentActivity(MainActivity.this, payment, 1);`

**Comment by vfoixcable** [comment]
indeed, there is a error in the readme. The request code has to be the same when calling `openPaymentActivity` and waiting for it in `onActivityResult` . The README was wrongly updated but MainActivity.java, as an example, is fine. ( https://github.com/sumup/sumup-android-sdk/blob/master/app/src/main/java/com/sumup/sdksampleapp/MainActivity.java )
The README will be corrected soon, thanks for highlighting
