### ISSUE TITLE
Currency CLP not provided in the SumUpPayment class

### ISSUE THREAD

**Issue by cfficaurzua** [sumup/sumup-android-sdk#34]
I have bought a sum up device called compraAqui in my country Chile
when i make a payment it returned the following message
Currency provided doesn't match merchant currency

i tried to change the following line
` .currency(SumUpPayment.Currency.EUR)` to
` .currency(SumUpPayment.Currency.CLP)`

but the SumUpPayment package doens't have CLP in the Currency enum

```
public static enum Currency {
        BGN("BGN"),
        BRL("BRL"),
        CHF("CHF"),
        CZK("CZK"),
        DKK("DKK"),
        EUR("EUR"),
        GBP("GBP"),
        HUF("HUF"),
        NOK("NOK"),
        PLN("PLN"),
        RON("RON"),
        SEK("SEK"),
        USD("USD");

        private final String isoCode;

        private Currency(String isoCode) {
            this.isoCode = isoCode;
        }

        public String getIsoCode() {
            return this.isoCode;
        }
    }
```

**Comment by vfoixcable** [comment]
Hi Cristóbal,

Indeed, we spotted that issue internally as well this week. The next version of the SDK (being v. 2.5.0) will add `CLP` as a Currency. It will be released by end of this week or beginning of next week!

Cheers
