### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by wynch** [sumup/sumup-android-sdk#35]
Hello,

Would you have any SDK documentation ? javadoc perhaps ?
I'd like to pair via Bluetooth a SumUp terminal using this SDK, and I can't figure out how...

**Comment by vfoixcable** [comment]
Hi,

Pairing is part of the SDK workflow and transparent for an integrator. The SDK workflow is  documented in the README

**Comment by wynch** [comment]
No, the SDK workflow isn't documented... What's documented is the 'standard' integration.

**Comment by wynch** [comment]
Not really... 
what's documented is only the 'standard' integration, but nowhere can I find :
- How do I set up a test ?
- Is there a more complex integration case using both API & SDK ? (to login automatically)
- what should I do in case of error ? (it seems some logout is needed to purge wrong credentials)

**Comment by jahenry** [comment]
Hi, Please contact integration@sumup.com with your use case and desired implementation.  The integration team are more than happy to assist.  Thanks

**Comment by wynch** [comment]
That's what I did, and after 4 days, they told me to look on your website and GitHub projects :-(

I'll see with them for further questions, thanks.
