### ISSUE TITLE
Duplicate affiliate key requests

### ISSUE THREAD

**Issue by claudiopaccone** [sumup/sumup-android-sdk#38]
With newest SDK's release (`2.5.1`) is requested to pass affiliate key both within `SumUpLogin` builder and within `SumUpPayment` builder.  
Furthermore, if affiliate key within `SumUpLogin` builder is not correct the `resultCode` obtained from `SumUpAPI.openLoginActivity` will be a `SumUpAPI.Response.ResultCode.SUCCESSFUL`response.   After that, if i pass the correct affiliate key to `SumUpAPI.checkout` the payment will be performed correctly and it generate an inconsistent situation.

**Comment by ismaellg** [comment]
Hey there. Are you also using an access token in `SumUpLogin`? If so your affiliate key is indeed being ignored. The next SDK version will deprecate the affiliate key at checkout so it will be only required in login. By version 3.0 it will be removed

**Comment by claudiopaccone** [comment]
Yes, i'm using an access token within SumUpLogin. I'll wait for next release, thanks

**Comment by vfoixcable** [comment]
Hi,
SDK 2.5.2 just got released: https://github.com/sumup/sumup-android-sdk/releases/tag/v2.5.2

Closing the issue!
