### ISSUE TITLE
Uncaught Unable to find explicit activity class / com.sumup.merchant.ui.Activities.LoginActivity

### ISSUE THREAD

**Issue by Encrypt-It** [sumup/sumup-android-sdk#39]
Hello.

I used the new Android Sumup Sdk to write my own module in Appcelerator. On the module creation itself was no problem, but when i started to use the new module in an app project, the following error is shown : Message: Uncaught Unable to find explicit activity class / com.sumup.merchant.ui.Activities.LoginActivity

the error is shown when i use SumUpAPI.openLoginActivity(activity, sumupLogin, 1);

Is there anyone who already got and solved this problem or has anyone an idea how to fix this :-) ?

Thanks :-)

**Comment by vfoixcable** [comment]
Hey hey,

Our Sdks are native and we currently only support native builds, however you may as some partners have done before, build your own wrapper for this integration.
Up to date, unfortunately we have not seen a Appcelerator wrapper from a partner that we could point you to. : /
