### ISSUE TITLE
ERROR_DUPLICATE_FOREIGN_TX_ID could be received but transaction is not exist

### ISSUE THREAD

**Issue by DenisYelkin** [sumup/sumup-android-sdk#47]
**Enviroment:** Sumup merchant-sdk 3.0.0; SumUp Air terminal

**Steps to reproduce:**
1. Call SumUpAPI.checkout with correct payment data and include foreign transaction ID.
2. When user would asked to insert card - turn off network connection.
3. Insert card into terminal.
4. Wait until "Connection lost" screen appear.
5. Turn on network connection.
6. Press "Dismiss" button.
7. Try to check transactions by "Foreign transaction ID" from payment data (in step 1): https://api.sumup.com/v0.1/me/transactions?foreign_transaction_id=[foreignTransactionID] (No transactions would be returned).
8. Call SumUpAPI.checkout with same payment data as on step 1.
9. Try to complete correct payment.

**Actual result:**
Error screen with message "Duplicate foreign transaction ID" will occurred. And returned result is ERROR_DUPLICATE_FOREIGN_TX_ID.

Please provide info: is it correct behavior? It will affect our implementation of working with SumUp API and SumUp SDK.

**Comment by jahenry** [comment]
Hi 
Can you please pass the MID/Email of account you're using to integration@sumup.com?  Along with a sample fx_trnx_id of this error for review.  
James

**Comment by DenisYelkin** [comment]
Hi
Unfortunately, account that I am using were provided for me by customer. And he do not want to provide account info on public web resource. I can provide to you examples of foreign transaction IDs witch I am using:
1) "db1c7d82-030e-453e-9994-4c4e50d25f40;0"
2) "db1c7d82-030e-453e-9994-4c4e50d25f40;1"
3) "dcc278ff-423c-48a1-94f7-c53f577c8d48;0"

Possibly I misunderstood you. Do you want to get account info on email: integration@sumup.com?
Denis

**Comment by jahenry** [comment]
Hi Denis
Yes please, please send further information (including account) to the email integration@sumup.com
James

**Comment by ambrose-at-cordic** [comment]
Thanks for the info on the usage of Transaction REST API when using foreign transaction IDs:

https://api.sumup.com/v0.1/me/transactions?foreign_transaction_id=<foreignTransactionID>

This usage isn't in the documentation for that  API:

https://developer.sumup.com/rest-api/#tag/Transactions

It resolved an issue for me when using that API with foreign tranaction ids.
