### ISSUE TITLE
Passive login feature

### ISSUE THREAD

**Issue by loicortola** [sumup/sumup-android-sdk#5]
In some use cases, the users using the utility app are not the account owners (example: Bartenders).
At first launch, it might be a problem to require the input of account credentials.

The SDK should allow an alternative way of logging into the app, via passing on an auth token from external middleware.

The customer would have to build a middleware which would call an API with the client's credentials and get an Auth Token in return which would be used to authenticate the app. 
I can concur this is something needed to provide a better UX.

NB: We are assuming multiple devices would be able to make payments from the same account. Imagine 4 bartenders each with the same app and their own device. This would have to be taken into account when delivering tokens.

API Proposition:
[GET] https://thesupersumupapi.com/auth/:deviceId
request headers would contain basic auth encoding of the credentials
returns 403: forbidden if failure / 200: Ok if OK.
The response could return something like {"token": "123456", "expires": "2015-04-11-17T16:39:00+00:00"}

The SumUpActivity flow would have an extra method taking a call back which may look like that:
```java
SumUpAPI.openPaymentActivity(MainActivity.this, ResponseActivity.class, payment, tokenAuthenticator);

interface SumUpTokenAuthenticator {
  Token requestToken();
}
```

Proposition of flow in the activity (I am assuming it kind of works like this, but obviously you will know better than me whether this makes sense or not):
SumUpActivity:
**1. Did I store a token in my SharedPreferences?**
-Yes:
  **2.1. - Proceed to payment. Did it work?**
  -Yes: Awesome.
  -No: Why?
    --Token expired: request new Token via the callback provided, and try again.
    --Invalid token: Error: throw RuntimeException or notify.
-No:
  **2.2. - request new Token via the callback provided, then go to 2.1.**

Please do not hesitate to enrich/elaborate this issue

**Comment by vfoixcable** [comment]
This feature is now part of the current SDK (v1.55.1) as an incubated feature and will be fully document from SDK v1.60
