### ISSUE TITLE
prepareForCheckout() has to be called twice the first time

### ISSUE THREAD

**Issue by larssn** [sumup/sumup-android-sdk#51]
So we're observing what appears to be a minor bug.

The first time after we've started our app and logged in, we have to call `prepareForCheckout()` twice in order for the terminal to wake up.

Subsequently, it seems to work; even after the device has entered hibernation.

**Comment by nuvoPoint** [comment]
I have a related issue where I sometimes get the following error when calling prepare:

`onTransportError() PinPlusReaderError{Name = TRANSPORT_ERROR mErrorCode=3}`

This results in that the pinpad does not prepare it self and the upcoming transaction take a long time.

**Comment by larssn** [comment]
We found a workaround where we don't call prepare if there currently is a bluetooth connection icon on the terminal.
