### ISSUE TITLE
Orientation for tablet

### ISSUE THREAD

**Issue by imran-samed** [sumup/sumup-android-sdk#59]
can we modify orientation as per device screen size...??

**Comment by imran-samed** [comment]
i got reply from support after 4-5 days.
and you asking me again to ask new query
What I'll do till  next 4-5 days ??

**Comment by imran-samed** [comment]
@imran-samed 

Supprot is so much lazy, they replying so late.

**Comment by imran-samed** [comment]
@jahenry 
Support is so much lazy, they replying so late :)

**Comment by jahenry** [comment]
@imran-samed I personally replied to your request within 24hrs.  Please feel free to reach out to integration@sumup.com again if you're still in need of support.
James
