### ISSUE TITLE
Consider support for Anroid 4.4

### ISSUE THREAD

**Issue by vladaman** [sumup/sumup-android-sdk#63]
Hi, I know this may be bit odd but there are MANY devices deployed which still run Android 4.4. They are mostly Chinese made POS systems with "stable" Android 4.4. Supporting newer Android devices you are virtually disconnecting all these standalone POS systems, which generally generate interesting transaction volumes compared to some smaller merchants.

**Comment by vfoixcable** [comment]
Hi, 
The minSdkVersion for our SDK is API 16. So technically, Android 4.4 is totally covered.

**Comment by digitalhoax** [comment]
minSdkVersion seems to be 26 nowadays, any chance you clean up the dependencies to get this below 26 anytime soon?

**Comment by vfoixcable** [comment]
Can you elaborate on your issue specifically? Our minSDK is still API 16.

**Comment by digitalhoax** [comment]
Sorry, I meant to write compileSdkVersion, which is 26.
