### ISSUE TITLE
Transparent authentication token is invalid

### ISSUE THREAD

**Issue by OshriDan** [sumup/sumup-android-sdk#64]
Hi all,

I'm trying to do login with an access token that I've received via a request to the https://api.sumup.com/token with Client credentials (aka grant_type= client_credentials, clientId and clientSecret) and I do receive back a token but when I try to login by calling:
`SumUpLogin sumupLogin = SumUpLogin.builder(mAffiliateKey).accessToken(token).build();
SumUpAPI.openLoginActivity(PrePaidActivity.this, sumupLogin, REQUEST_CODE_SUMUP_LOGIN);`
I keep on getting in the onActivityResult SumUpAPI.Response.ResultCode.ERROR_INVALID_TOKEN as response.
When I try to do login without the access_token and insert my user credentials everything goes fine and I can login, connect to the card reader and make payments.

please help!

**Comment by gi097** [comment]
Indeed. Also worth noting is that the login flow only works when using a username/password combination. It seems that the token length is smaller when using `client_credentials` as grant type. Is this not available at all in the Android SDK?

**Comment by jahenry** [comment]
Hi @OshriDan and @gi097 thanks for reaching out and my apologies for the delayed response.  Login with token does work with the SumUp Android SDK but please use the Authorization_Code grant type: https://developer.sumup.com/docs/authorization#authorization-flows this allows you to authenticate as a SumUp merchant vs an application.

**Comment by gi097** [comment]
So this means that there is no way to do a silent automatic login, except when using a username and password? That's a pity.

**Comment by JullianSU** [comment]
Hi @gi097 

As the Application access private data, a first login with consent from merchant via Authorization_Code grant type is mandatory. 

Many thanks,

**Comment by nowjordanhappy** [comment]
Hi, I'm having the same issue, so using the tokend I got from this, is not working.
<img width="851" alt="imagen" src="https://github.com/sumup/sumup-android-sdk/assets/26355419/aa431534-bce3-41ff-abbc-06a9c7090301">

Are you saying there's no way to make this work using an automatic login? I'm contacting the integration team but not get response.
