### ISSUE TITLE
two stage or Pre-Authorization supported?

### ISSUE THREAD

**Issue by audiserg** [sumup/sumup-android-sdk#65]
In our project we need authorize card via SumUp terminal, and after 5-10 minutes for customers activity calculate total amount and do checkout. We need only one card reading on first stage!!!   In other device present pre-authorization or something  like here https://docs.adyen.com/developers/point-of-sale/build-your-integration/payment-features/acquire-card-details, or may be we can do that via tips without second  card reading, may be  sdk support read card info and then we will use rest api?

**Comment by JullianSU** [comment]
Hello, 

This feature is not available with our current SDK/API. We will keep you informed if something is going in that direction in the future. 

Many thanks,
