### ISSUE TITLE
Cancel payment issue in Android device.

### ISSUE THREAD

**Issue by ils-aashishj** [sumup/sumup-android-sdk#66]
Hi,
I am getting issue while waiting for the device to connect. When I tap on cancel button on Bluetooth screen it always redirects to the same screen again and again so how can I cancel on a single click.

![screenshot_20190125-123018](https://user-images.githubusercontent.com/10892973/51730440-854ed080-209d-11e9-9191-932c04206c2c.png)

**Comment by JullianSU** [comment]
Hi Ashsih, 

I have answered directly to your email at integration@sumup.com. I will post the final answer later on this thread. 

Many thanks,
