### ISSUE TITLE
Sumup terminal fails to connect to our app.....

### ISSUE THREAD

**Issue by ambrose-at-cordic** [sumup/sumup-android-sdk#68]
Hello,

We have found issues with our failing to connect to the SumUp Terminal when oerforming the checkout process.

In using the phones and SumUp device from 24x7 cars (which regularly exhibited the issue in the field):

    Phone 
    Model: Samsung Galaxy J5
    Android Version: Marshmallow / v6.0.1 / API Level 23

    Software:
    cPAQ Mobile App using SumUp SDK v2.5.3
    SumUpSDK Sample App for SumUp SDK 3.1.2 

    Card Reader:
    Model: SumUp Air Card Reader (AIR1E205)
    Device Number: 105018480517

In each of these environments, I had issues with connection to the device was  when the following was performed:

    - Using any of the aforementioned apps:
       - Login to the SumUpSDK 
        - Start a checkout process to make a payment.
      - If the process is successfully completed and the bluetooth icon on device does not disappear, on the next attempt to start a checkout process, you will find that it fails to make a connection with the reader (waiting more than 3 minutes), repeatedly showing the following errors in logcat:

        02-18 10:11:16.019 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.019 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.019 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.019 3240-3376/? D/BtGatt.GattService: onClientRegistered() - UUID=f1928b16-c9e1-4f0b-a18c-18c1dfc54f58, clientIf=0
        02-18 10:11:16.019 3240-3376/? D/BtGatt.GattService: onClientRegistered() - mClientMap: 28, mServerMap: 0
        02-18 10:11:16.029 8311-8321/? D/BluetoothGatt: onClientRegistered() - status=133 clientIf=0
        02-18 10:11:16.029 8311-9700/? W/SumUp: (SourceFile:113)@BtSmart-Receiver | BluetoothAdapter not initialized
        02-18 10:11:16.129 8311-8311/? E/SumUp: (SourceFile:150)@main | onTransportError() PinPlusReaderError{Name = TRANSPORT_ERROR mErrorCode=3}
        02-18 10:11:16.129 8311-8311/? W/SumUp: (SourceFile:46)@main | Tried to start event, but last event was not finished
        02-18 10:11:16.139 8311-8311/? D/BluetoothGatt: connect() - device: EC:EB:47:B8:30:34, auto: false
        02-18 10:11:16.139 8311-8311/? D/BluetoothGatt: registerApp()
        02-18 10:11:16.139 8311-8311/? D/BluetoothGatt: registerApp() - UUID=3a943722-6f45-46ae-a7f0-ec3d3fd65ee9
        02-18 10:11:16.139 3240-3256/? D/BtGatt.GattService: registerClient() - UUID=3a943722-6f45-46ae-a7f0-ec3d3fd65ee9
        02-18 10:11:16.239 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.239 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.239 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.239 3240-3376/? D/BtGatt.GattService: onClientRegistered() - UUID=3a943722-6f45-46ae-a7f0-ec3d3fd65ee9, clientIf=0
       02-18 10:11:16.239 3240-3376/? D/BtGatt.GattService: onClientRegistered() - mClientMap: 28, mServerMap: 0
        02-18 10:11:16.249 8311-8925/? D/BluetoothGatt: onClientRegistered() - status=133 clientIf=0
        02-18 10:11:16.259 8311-9702/? W/SumUp: (SourceFile:113)@BtSmart-Receiver | BluetoothAdapter not initialized
        02-18 10:11:16.359 8311-8311/? E/SumUp: (SourceFile:150)@main | onTransportError() PinPlusReaderError{Name = TRANSPORT_ERROR mErrorCode=3}
        02-18 10:11:16.359 8311-8311/? W/SumUp: (SourceFile:46)@main | Tried to start event, but last event was not finished
        02-18 10:11:16.359 8311-8311/? D/BluetoothGatt: connect() - device: EC:EB:47:B8:30:34, auto: false
        02-18 10:11:16.359 8311-8311/? D/BluetoothGatt: registerApp()
        02-18 10:11:16.359 8311-8311/? D/BluetoothGatt: registerApp() - UUID=26c09a6e-be00-4920-964f-0991de09e20a
        02-18 10:11:16.369 3240-3767/? D/BtGatt.GattService: registerClient() - UUID=26c09a6e-be00-4920-964f-0991de09e20a
        02-18 10:11:16.469 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.469 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.469 3240-3749/? E/bt_btif: Register with GATT stack failed.
        02-18 10:11:16.469 3240-3376/? D/BtGatt.GattService: onClientRegistered() - UUID=26c09a6e-be00-4920-964f-0991de09e20a, clientIf=0
        02-18 10:11:16.469 3240-3376/? D/BtGatt.GattService: onClientRegistered() - mClientMap: 28, mServerMap: 0
        02-18 10:11:16.469 8311-8321/? D/BluetoothGatt: onClientRegistered() - status=133 clientIf=0
        02-18 10:11:16.479 8311-9704/? W/SumUp: (SourceFile:113)@BtSmart-Receiver | BluetoothAdapter not initialized
        02-18 10:11:16.579 8311-8311/? E/SumUp: (SourceFile:150)@main | onTransportError() PinPlusReaderError{Name = TRANSPORT_ERROR mErrorCode=3}
        02-18 10:11:16.579 8311-8311/? W/SumUp: (SourceFile:46)@main | Tried to start event, but last event was not finished
        02-18 10:11:16.589 8311-8311/? D/BluetoothGatt: connect() - device: EC:EB:47:B8:30:34, auto: false
        02-18 10:11:16.589 8311-8311/? D/BluetoothGatt: registerApp()
        02-18 10:11:16.589 8311-8311/? D/BluetoothGatt: registerApp() - UUID=c3fb2223-f307-45ba-83ef-474b8cb779d6
        02-18 10:11:16.589 3240-9531/? D/BtGatt.GattService: registerClient() - UUID=c3fb2223-f307-45ba-83ef-474b8cb779d6

It has also noted that it the reader has been left idle overnight, the first attempt to make a payment also fails in the same way with the same aforementioned errors shown in logcat.

**Comment by rasson** [comment]
I have exactly the same issue - when the bluetooth symbol stays up the next transaction will not connect and the first transaction of the day is also a problem

**Comment by JullianSU** [comment]
Hi Rasson, 

Are you using the prepareForCheckout option? Feel free to share a video of the behavior at integration@sumup.com. 

Many thanks,

**Comment by ambrose-at-cordic** [comment]
We were using it and found it made no difference, the problem still occured, We thought it was due to it being called too close to when the transaction was sent, so we change the call to happen earlier in job progression to give it more time, but it caused other issues as well as not resolving the issue.

The workaround we used was to force  a resync of the bt cache between the device and the reader, which has resolved this type of issue in most cases.

**Comment by rasson** [comment]
Hi Julian

Yes, we are using the 'preparefortransaction' and it REALLY helps when starting a bluetooth connection prior to a transaction.  

However the issue most people are describing and the one we have is actually caused by the last successful transaction.  Every so often (I make it to be about every 5th transaction) the bluetooth connection hangs AT THE END of a successful transaction.  This in turn prevents the next bluetooth connection being formed as the card reader is still occupied with the last connection.  

Can you help?

**Comment by rasson** [comment]
@ Ambrose

Hi

Would you mind sharing the code that forces a resync of the BT acche?

Thank you sooo much in adavnce :-)

**Comment by elroyfernandes** [comment]
We are also experiencing this issue, even with the latest release. @JullianSU when can we expect a fix?
