### ISSUE TITLE
SumUp + Ionic/Cordova

### ISSUE THREAD

**Issue by epicazo** [sumup/sumup-android-sdk#69]
Hello,

Currently working on this from a project started 2 years ago. Back in the days made it work on android with the v2.3.0 but now with the v3.1.2 after loggin in I'm not prompted to pair my terminal payment to my phone anymore, did something change in the SDK and I have to do something else or there is a problem in the call I make ?

I can't find any documentation on how to make the calls, what to expect from the said call or just the listing of every function there is with their implementation, except what we have in the read me of the SDK (which is not much)

Anyone made SumUp work with a Ionic or Cordova application ?

**Comment by oualaeddine** [comment]
hello @epicazo  i've found this library , i think it might help you [https://github.com/nuvoPoint/cordova-plugin-sumup](https://github.com/nuvoPoint/cordova-plugin-sumup)
