### ISSUE TITLE
Landscape mode support

### ISSUE THREAD

**Issue by hardikp888** [sumup/sumup-android-sdk#7]
How can I set landscape mode using sumup-android-sdk for sumup Payment screens ?

**Comment by vfoixcable** [comment]
Landscape mode is supported on tablets only (sw600 dp and up). On these devices the SumUp Android SDK follows the screen orientation set by the user. On phones, the orientation is always in portrait mode.

**Comment by hardikp888** [comment]
Is there any way (Any function in sumup-sdk) for landscape mode in android device (800x480) ?

**Comment by vfoixcable** [comment]
Could you share with us which Android device you are referencing and why your use case requires landscape mode?
For design reason, if the device is a phone, we don't allow a switch to portrait mode and we don't provide any method to change this behaviour.

**Comment by flixbernard** [comment]
Dear all,

I'm experiencing a similar problem on Galaxy Tab 3 landscape mode. When the App launches, it turns portrait for about 1 second and then goes to landscape.
Is there any chance that this small parasite turn would be avoided ?
Thank you in advance !

Best regards,

Félix

**Comment by milenpav** [comment]
you need to set recource   
  <bool name="isTablet">true</bool>
