### ISSUE TITLE
Login Works intermittently

### ISSUE THREAD

**Issue by csjames** [sumup/sumup-android-sdk#70]
Our app users are finding that login may eventually stop working (when supplied with the correct credentials).

It appears a reinstall of the application solves this problem.

Additionally, using a different device, with the same credentials will work

We are on the newest version of the SDK

**Comment by JullianSU** [comment]
Hi James, 

Would you be able to send an email explaining a bit more in-depth the issue and how to reproduce it at integration@sumup.com with more details: 

- MIDs
- OS
- Affiliate key

Many thanks,
