### ISSUE TITLE
skipSuccessScreen not working

### ISSUE THREAD

**Issue by legolas108** [sumup/sumup-android-sdk#71]
We are new to SumUp and have just begun integrating with our POS system. When initiating a payment the `skipSuccessScreen` option is not working on the reader we were provided with without choice for another one. Documentation says, this is by design for the SumUp Air Lite readers, so the main reader currently provided doesn't support this option.

It would be **much** appreciated if this option could also be made available for this reader, because we have a more convenient way of providing our customers with e-receipts that e.g. include all product details also.

Thanks so much for considering!
Ole

**Comment by JullianSU** [comment]
Hi, 

The skipSuccessScreen option is not available for the AirLite for user experience purposes. As the reader as no screen to show the result of the transaction, we force the success screen in the flow. 

Many thanks,

**Comment by larssn** [comment]
@JullianSU He knows that. He's simply asking for more freedom in the matter.
