### ISSUE TITLE
Session expire after some time

### ISSUE THREAD

**Issue by gheorghe96** [sumup/sumup-android-sdk#73]
After several hours of inactivity, when try to make a payment, I receive an error saying that session expired.
Every time this error is shown in a different language.
Although before every payment I refresh token from server.
When try to do that one more time it works fine.
![Screenshot_20190311-113236](https://user-images.githubusercontent.com/20193904/54115057-6f4e6280-43f4-11e9-878b-96ab889e123b.jpg)
(Votre session a expire. Veuillez vous conecter et reessayer)

**Comment by rasson** [comment]
I get this too

**Comment by JullianSU** [comment]
Hi, 

I suspect this is a token issue, the problem occurs when you do not finish checkout and try again later? 

Feel free to reach out at integration@sumup.com, I will follow up here when we have a clear diagnostic and solution. 

Many thanks,

**Comment by rasson** [comment]
Hi Julian

I too think it's a token issue - am I right in thinking there are 2 different tokens?  If so, is one for logging in and the other for sending transactions?

**Comment by JullianSU** [comment]
Hi Rasson, 

Indeed there are 2 different types of Token: 

- **Access token** which is valid for 1H and it is required for any action you would like to perform on behalf of the merchant (transparent login, using REST API, etc) 
- **Refresh_token** which is technically valid for 6 months, once your **access_token** expired you will need to request a new one by using the **Refresh_token**.

I hope this is good help!
