### ISSUE TITLE
questions on the tip facility in the SumUp SDK....

### ISSUE THREAD

**Issue by ambrose-at-cordic** [sumup/sumup-android-sdk#76]
Hello,

In lokking at the provided documentation on the tip feature, it seems that its just an amount that provided as part of the payment request as opposed to say an option offered to the customer prior to payment via the SDK.

Is that correct?

**Comment by JullianSU** [comment]
Hi, 

Indeed the tips parameter is processed during the same checkout as the main transaction. What would be your use case for having 2 separate checkouts for transaction & tips? 

Many thanks,

**Comment by ambrose-at-cordic** [comment]
I just wondered if the tip facility in the SDK included offering the option to payee to leave a tip via the card reader or leaves the obtaining of the tip amount to the developer and provides that amount as part of the payment request.
