### ISSUE TITLE
Affiliate key invalid even though it is valid

### ISSUE THREAD

**Issue by tomde** [sumup/sumup-android-sdk#77]
I started to get error Invalid Affiliate key when i start the payment.
Now using sdk v3.1.2. and tried on Android 6.0 and 8.1

**Comment by JullianSU** [comment]
Hi Tomde, 

Thank you for your message and sorry for the late reply. Would you be able to share with us at integration@sumup.com a bit more on your issue and how did you get your affiliate key? 

Many thanks, 
Jullian

**Comment by PhilSim777** [comment]
Hi,
I experiment the same issue on the developper account, trying to generate a new  affiliate key, but only the one provided by Android SDK works fine.
Does it mean that  affiliate key generation using the developper account is not valid ?

Thanks in advance,
BR,
Philippe

**Comment by guyvaio** [comment]
Does sumup still supports SDK and app integration? Probably not! integration@sumup.com does not give support anymore. No reaction.
