### ISSUE TITLE
SumUp Total is compatible with SDK?

### ISSUE THREAD

**Issue by ulissesc** [sumup/sumup-android-sdk#79]
Is the Android SDK compatible with SumUP Total?

Here is the link for it: https://sumup.com.br/maquinas-de-cartao/total/

**Comment by niddey** [comment]
Will you also be adding support for the SumUp 3G reader in the next update? I noticed the ios sdk already has support for this.

**Comment by JullianSU** [comment]
Hi Ulissesc, Hi Niddey, 

The **SumUp Total** reader is designed to work in full autonomy, there is no plan to have it compatible with the SDK. 

The  **SumUp 3G** will be compatible on the next release of the SDK, you will be able to use it in Bluetooth connection (same as the AIR device). 

Many thanks,
