### ISSUE TITLE
SumUp SDK uses unsafe dependency/library

### ISSUE THREAD

**Issue by Brianvdb** [sumup/sumup-android-sdk#80]
We have published an app in the Play Store and now the Play Developer console is showing the following warning:
![warning](https://i.imgur.com/KDDxxhQ.png)
As you can see, this vulnerability happens in the `org.puredata.core.utils.IoUtils.extractZipResource` method.

I checked the app dependencies with the command:
`./gradlew app:dependencies` 

This shows that the SumUp SDK uses the puredata library which causes this warning.
![dependencies](https://i.imgur.com/WmvsGms.png)

Can this be fixed?

**Comment by JullianSU** [comment]
Hi Brianvdb, 

Thank you for raising this alert. We are aware of the situation and already working on a fix for the next release of the SDK. This should happen in the next 4 weeks. 

Many thanks,

**Comment by JullianSU** [comment]
Hi Brianvdb, 

Sorry for the late reply, we have solved the issue in SDK 3.2.0 to align with the new 64 bits requirement for the PlayStore.

Many thanks,
