### ISSUE TITLE
libepos2.so is written on 64 bit 

### ISSUE THREAD

**Issue by pramodkr123** [sumup/sumup-android-sdk#81]
you are using jniLibs-> armeabi->libepos2.so is written on 64 bit ?

I am using this .so file in my app, and now it required to use 64 bit library in app.

**Comment by JullianSU** [comment]
Hi Pramodkr123, 

Sorry for the late reply, we have solved the issue in SDK 3.2.0 to align with the new 64 bits requirement for the PlayStore. 

Many thanks,
