### ISSUE TITLE
Question: 64 bit support ?

### ISSUE THREAD

**Issue by wynch** [sumup/sumup-android-sdk#82]
Hello !

I'm trying to prepare my android app for 64 bits support, because Google will only accept apps with 64 bits executable starting 1 of august 2019. (https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html)

Looking through my app dependencies, it seems SumUp SDK relies on dependencies which are not 64 bits-ready : (org.puredata.android:pd-core:1.0.2), although I'm not sure.

Have you planned a release for this ?

**Comment by rasson** [comment]
Hi Julian

Does this mean any apps developed to date will stop working on the 1st August?

**Comment by wynch** [comment]
Julian?

No, apps with only 32bit support will continue working till 1 august 2021. 

But you won't be able to submit new versions of your app without 64bit support

**Comment by JullianSU** [comment]
Hi Wynch, Hi Rasson, 

Thank you for your message and I understand your concerns. We are currently on a new release and we will remove the dependencies causing troubles. The next release is planned in the next couple of weeks. 

Many thanks,

**Comment by rasson** [comment]
Thanks Julian

Will the new release tackle the known bluetooth issues too?
