### ISSUE TITLE
Sumup SDK with selfservice application

### ISSUE THREAD

**Issue by Wicher95** [sumup/sumup-android-sdk#83]
Hi,

Reading license and sumup website I can't find clear infromation about using sumup with selfservice application. The application I'm developing is for restauratns where client can come and take an order all by himself by paying with credit card ofcourse. Can I use your SDK and terminals (Sumup Air) in this kind of application?

Best Regards,
Piotr WIcher

**Comment by JullianSU** [comment]
HI Wicher95, 

Thank you for your message, there are different parameters to take in consideration here. Does the payment solution is fully independent or some staff members will be around to support the customers? 

If you want to provide more details, please contact us directly at integration@sumup.com. 

Many thanks, 
Jullian.
