### ISSUE TITLE
[STRING RESOURCES FILE] Error in compilation

### ISSUE THREAD

**Issue by SoftwareAdvise** [sumup/sumup-android-sdk#84]
i have to set formatted = false to strings.
Files:
![immagine](https://user-images.githubusercontent.com/9363586/59608986-cd3ac680-9116-11e9-9ede-ce58f19d408b.png)
![immagine](https://user-images.githubusercontent.com/9363586/59609001-d5930180-9116-11e9-941f-274cc262ce1f.png)
![immagine](https://user-images.githubusercontent.com/9363586/59609014-dcba0f80-9116-11e9-9727-d7e023acb721.png)

and others on the same string

**Comment by PaolinoAngeletti** [comment]
GREAT! YOU CLOSE ISSUES DOING NOTHING! YOU'RE GREAT ;)
