### ISSUE TITLE
Skip last step ( email / sms )

### ISSUE THREAD

**Issue by ulissesc** [sumup/sumup-android-sdk#9]
Can i skip the last step of the SDK, which ask to inform the email / sms? I think this step should be optional.

**Comment by ivanperezde** [comment]
Hi Ulisses, as part of EMV compliance we must allow the end user the option to receive a receipt containing the EMV block. For this reason we cannot remove the option.
We will provide a receipt service which will allow you to handle the block at a later date. We will inform you when this is ready.

**Comment by ulissesc** [comment]
For future improvements would be very interesting if I could recover the payment method chosen by the customer . Example : Debit or credit.

**Comment by vfoixcable** [comment]
Skip success screen is now available from version 2.3.0 -- see README for more
