### ISSUE TITLE
Wrong PIN gets accepted sometimes

### ISSUE THREAD

**Issue by michaelprankl99** [sumup/sumup-android-sdk#91]
Hello,
I have the problem that sometimes when I enter a wrong PIN the payment still is approved by the sumup terminal.
Can someone help me with this issue?

**Comment by JullianSU** [comment]
Hi Michael, 

Thank you for your message, are you using a test account that we have provided to you or it is happening on regular SumUp account. Please share your account details at integration@sumup.com and I will be able to look more into details. 

Many thanks,

**Comment by michaelprankl99** [comment]
I am using a test account. I totally forgot about that. Thanks!
