### ISSUE TITLE
AuthenticateWithToken does not work

### ISSUE THREAD

**Issue by GustasI** [sumup/sumup-android-sdk#97]
After receiving the access_token from the sum up API, using the grant_type 'password', I try and call AuthenticateWithToken. This returns [Error: Invalid Token] without any other explanation. I am positive the affiliate key is from the account that I use to receive the access token with.

**Comment by JullianSU** [comment]
Hi Gustasl 

Thank you for contacting us, could you please send an email at integration@sumup.com with the client_id that you are using to issue the token. 

Many thanks,

**Comment by Furiacs** [comment]
@GustasI look this: https://github.com/sumup/sumup-android-sdk/issues/45#issuecomment-426957816

I had the same problem and it was resolved this way.

**Comment by GustasI** [comment]
@Furiacs did try this solution, the token I receive with grant_type password is the one, that does not work.

**Comment by Furiacs** [comment]
@GustasI did you try this?

```
{
    grant_type: 'password',
    client_id: 'client id created in SumUp control panel',
    username: 'your account username',
    password: 'your account password'
}
```

This way really works for me...

**Comment by JullianSU** [comment]
Hi Furiacs, 

The issue was different and now solved. Thank you for your contribution to this topic. 

Many thanks,
